const fs   = require('fs');
const path = require('path');

try {
  const htmlPath   = path.join(__dirname, 'index.html');
  const workerPath = path.join(__dirname, 'worker.js');

  const html = fs.readFileSync(htmlPath, 'utf8');
  const escapedHtml = JSON.stringify(html);

  // ── Helper: read JSON, return fallback on missing/invalid ──
  const readJson = (file, fallback = {}) => {
    const p = path.join(__dirname, file);
    if (!fs.existsSync(p)) return fallback;
    try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
    catch (e) { console.warn(`  ⚠ Invalid JSON: ${file} — ${e.message}`); return fallback; }
  };

  // ── Game data ─────────────────────────────────────────
  const ps1 = readJson('ps1.json', []);
  const ps2 = readJson('ps2.json', []);
  const ps3 = readJson('ps3.json', []);
  const dub = readJson('Dub.json', []);
  const sub = readJson('Sub.json', []);

  console.log(`  📦 ps1: ${ps1.length} | ps2: ${ps2.length} | ps3: ${ps3.length}`);
  console.log(`  🎬 dub: ${dub.length} | sub: ${sub.length}`);

  // ── Cover maps ────────────────────────────────────────
  // libretro format: { "cleankey": "https://thumbnails.libretro.com/..." }
  // PlayStation_3_HighRes format: [{ title, cover_url }]
  const coverMap = {};

  const lps1 = readJson('libretro_ps1.json', {});
  const lps2 = readJson('libretro_ps2.json', {});
  const lps3 = readJson('libretro_ps3.json', {});
  // Merge all libretro maps (keys are already clean)
  Object.assign(coverMap, lps1, lps2, lps3);

  // Also merge HighRes arrays if present
  const ps3hr = readJson('PlayStation_3_HighRes.json', []);
  if (Array.isArray(ps3hr)) {
    ps3hr.forEach(item => {
      if (item && item.title && item.cover_url) {
        const k = item.title.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (k) coverMap[k] = item.cover_url;
      }
    });
  }

  console.log(`  🖼  coverMap keys: ${Object.keys(coverMap).length}`);

  // ── Scraper metadata ──────────────────────────────────
  const scraperMeta = {
    lastRun: fs.existsSync(path.join(__dirname, '.scraper-last-run'))
      ? fs.readFileSync(path.join(__dirname, '.scraper-last-run'), 'utf8').trim()
      : null,
    dubCount: dub.length,
    subCount: sub.length,
  };

  // ── Embed all data directly (no worker-side imports needed) ──
  // We inline ps1/ps2/ps3 as JSON strings and pass coverMap inline.
  // This avoids Cloudflare Workers' 1MB KV limit and import issues.
  const gamesJson  = JSON.stringify({ ps1, ps2, ps3, dub, sub });
  const coversJson = JSON.stringify(coverMap);
  const metaJson   = JSON.stringify(scraperMeta);

  const inject = `<script>\nwindow.__GAMES=${gamesJson};\nwindow.__COVERS=${coversJson};\nwindow.__META=${metaJson};\n</script>`;
  const finalHtml = html.replace('</head>', inject + '</head>');
  const escapedFinal = JSON.stringify(finalHtml);

  const lines = [
    `// Auto-generated by build.js — ${new Date().toISOString()}`,
    ``,
    `const CORS = {`,
    `  'Access-Control-Allow-Origin': '*',`,
    `  'Access-Control-Allow-Methods': 'GET, OPTIONS',`,
    `  'Access-Control-Allow-Headers': 'Content-Type',`,
    `};`,
    ``,
    `const HTML = ${escapedFinal};`,
    ``,
    `const htmlRes = b => new Response(b, {`,
    `  headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=900', ...CORS }`,
    `});`,
    ``,
    `export default {`,
    `  async fetch(req) {`,
    `    const url  = new URL(req.url);`,
    `    const path = url.pathname.replace(/\\/+$/, '') || '/';`,
    `    if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });`,
    `    if (path === '/manifest.json') {`,
    `      return new Response(JSON.stringify({`,
    `        name: 'مكتبة الألعاب العربية',`,
    `        short_name: 'PS Games',`,
    `        start_url: '/',`,
    `        display: 'standalone',`,
    `        background_color: '#060408',`,
    `        theme_color: '#060408',`,
    `        icons: [{ src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%23e8b84b"/><text x="50" y="68" text-anchor="middle" fill="%23000" font-size="36" font-weight="bold" font-family="sans-serif">PS</text></svg>', sizes: '192x192', type: 'image/svg+xml' }]`,
    `      }), { headers: { 'Content-Type': 'application/json', ...CORS } });`,
    `    }`,
    `    return htmlRes(HTML);`,
    `  }`,
    `};`,
  ];

  fs.writeFileSync(workerPath, lines.join('\n'), 'utf8');
  const sizeMB = (fs.statSync(workerPath).size / 1024 / 1024).toFixed(2);
  console.log(`\n✅ worker.js generated — ${sizeMB} MB`);

  if (parseFloat(sizeMB) > 25) {
    console.warn(`  ⚠ worker.js is ${sizeMB} MB — Cloudflare Workers limit is ~25 MB gzipped`);
  }

} catch (err) {
  console.error('❌ Build error:', err);
  process.exit(1);
}
